# Generated by Django 4.2.5 on 2023-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
